[package]
name = "rekordcrate"
version = "0.3.0"
authors = ["Jan Holthuis <jan.holthuis@ruhr-uni-bochum.de>"]
description = "Library for parsing Pioneer Rekordbox device exports"
readme = "README.md"
repository = "https://github.com/Holzhaus/rekordcrate"
license = "MPL-2.0"
keywords = ["rekordbox", "dj", "export", "database", "parser"]
categories = ["parser-implementations"]
edition = "2021"
exclude = [".*"]

[dependencies]
binrw = "0.15"
modular-bitfield = "0.13"
crc16 = "0.4"
clap = { version = "4.5", features = ["derive"], optional = true }
parse-display = "0.10"
thiserror = "2.0"
quick-xml = { version = "0.38.4", features = ["serialize", "serde-types"] }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
fallible-iterator = "0.3.0"
diesel = { version = "2.3.7", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "64-column-tables"], optional = true }
diesel-derive-newtype = { version = "2.1.2", optional = true }
libsqlite3-sys = { version = "0.36.0", features = ["bundled-sqlcipher"], optional = true }
[build-dependencies]
glob = "0.3"

[dev-dependencies]
pretty-hex = "0.4"
pretty_assertions = "1"
tempfile = "3"

[features]
default = ["cli"]
cli = ["dep:clap"]
device_library_plus = ["dep:diesel", "dep:diesel-derive-newtype", "dep:libsqlite3-sys"]

[[bin]]
name = "rekordcrate"
required-features = ["cli"]
